--PROJECT2 / project22
CREATE SEQUENCE REVIEW_SEQ NOCACHE;
CREATE SEQUENCE ACCOUNT_SEQ NOCACHE;
CREATE SEQUENCE MOVIE_SEQ NOCACHE;
INSERT INTO ACCOUNT
VALUES (ACCOUNT_SEQ.NEXTVAL, '홍길동', 'hong1', '1111', 'ace119', 0, 'hong@naver.com');
INSERT INTO ACCOUNT
VALUES (ACCOUNT_SEQ.NEXTVAL, '김유신', 'kim3', '3333', 'kys106', 0, 'you@naver.com');
INSERT INTO ACCOUNT
VALUES (ACCOUNT_SEQ.NEXTVAL, '이순신', 'lee4', '4444', 'lss330', 0, 'shin@gmail.com');
--NO, NAME, ID, PWD, NICK, CRITIC_CHECK, EMAIL
SELECT * FROM ACCOUNT;

INSERT INTO MOVIE
VALUES (MOVIE_SEQ.NEXTVAL, '파묘', '장재현', '최민식,김고은,유해진,이도현', '미스터리'
      , 8.21, '1,164만명', '전체연령', '20240222', '포스터 파일경로');
--M_NO,M_TITLE,M_DIRECT,M_ACTOR,M_GENRE,M_RATE,M_AUDIENCE,M_GRADE,M_DATE,M_POSTER
SELECT * FROM MOVIE;

INSERT INTO REVIEW
--    R_NO, M_NO, A_NO, R_NICK, R_TITLE
--  , R_CONTENT, R_DATE, R_REC
VALUES (REVIEW_SEQ.NEXTVAL, 1, 2, 'ace119', '재밌음ㅋㅋ'
      , '원래 이런 장르 즐겨보지 않는데 연기력이 받쳐주니 빠져들어서 시간 순삭!!', SYSDATE, 0);
INSERT INTO REVIEW
VALUES (REVIEW_SEQ.NEXTVAL, 1, 3, 'kys106', '강추bb'
      , '너무 재밌어요ㅠㅠ', SYSDATE, 0);
INSERT INTO REVIEW
VALUES (REVIEW_SEQ.NEXTVAL, 1, 4, 'lss330', '인생영화'
      , '간만에 볼 영화 생겼음ㅎㅎ', SYSDATE, 0);
SELECT * FROM REVIEW;