--selectAll
SELECT R.*, M.*
FROM REVIEW R, MOVIE M
WHERE R.M_NO = M.M_NO
;

--selectOne
--M_TITLE 검색
SELECT R.*, M.*
FROM REVIEW R, MOVIE M
WHERE R.M_NO = M.M_NO
AND M.M_TITLE = '파묘'
ORDER BY R.R_NO DESC
;
--R_NICK 검색
SELECT R.*, M.*
FROM REVIEW R, MOVIE M
WHERE R.M_NO = M.M_NO
AND R.R_NICK = 'ace119'
ORDER BY R.R_NO DESC
;
--R_DATE
SELECT M.M_TITLE, R.R_TITLE, R.R_NICK, R.R_DATE, R.R_REC 
FROM REVIEW R, MOVIE M
WHERE R.M_NO = M.M_NO
AND TO_CHAR(R.R_DATE, 'YYYYMMDD') = '20240417'
ORDER BY R.R_NO DESC
;

--
